// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/directory/reader/v2/reader.proto

// Protobuf Java Version: 3.25.3
package com.aserto.directory.reader.v2;

/**
 * Protobuf type {@code aserto.directory.reader.v2.GetObjectResponse}
 */
public final class GetObjectResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aserto.directory.reader.v2.GetObjectResponse)
    GetObjectResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetObjectResponse.newBuilder() to construct.
  private GetObjectResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetObjectResponse() {
    relations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetObjectResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aserto.directory.reader.v2.ReaderProto.internal_static_aserto_directory_reader_v2_GetObjectResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aserto.directory.reader.v2.ReaderProto.internal_static_aserto_directory_reader_v2_GetObjectResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aserto.directory.reader.v2.GetObjectResponse.class, com.aserto.directory.reader.v2.GetObjectResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RESULT_FIELD_NUMBER = 1;
  private com.aserto.directory.common.v2.Object result_;
  /**
   * <pre>
   * object instance
   * </pre>
   *
   * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
   * @return Whether the result field is set.
   */
  @java.lang.Override
  public boolean hasResult() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * object instance
   * </pre>
   *
   * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
   * @return The result.
   */
  @java.lang.Override
  public com.aserto.directory.common.v2.Object getResult() {
    return result_ == null ? com.aserto.directory.common.v2.Object.getDefaultInstance() : result_;
  }
  /**
   * <pre>
   * object instance
   * </pre>
   *
   * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
   */
  @java.lang.Override
  public com.aserto.directory.common.v2.ObjectOrBuilder getResultOrBuilder() {
    return result_ == null ? com.aserto.directory.common.v2.Object.getDefaultInstance() : result_;
  }

  public static final int RELATIONS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.aserto.directory.common.v2.Relation> relations_;
  /**
   * <pre>
   * object relations
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
   */
  @java.lang.Override
  public java.util.List<com.aserto.directory.common.v2.Relation> getRelationsList() {
    return relations_;
  }
  /**
   * <pre>
   * object relations
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.aserto.directory.common.v2.RelationOrBuilder> 
      getRelationsOrBuilderList() {
    return relations_;
  }
  /**
   * <pre>
   * object relations
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
   */
  @java.lang.Override
  public int getRelationsCount() {
    return relations_.size();
  }
  /**
   * <pre>
   * object relations
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
   */
  @java.lang.Override
  public com.aserto.directory.common.v2.Relation getRelations(int index) {
    return relations_.get(index);
  }
  /**
   * <pre>
   * object relations
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
   */
  @java.lang.Override
  public com.aserto.directory.common.v2.RelationOrBuilder getRelationsOrBuilder(
      int index) {
    return relations_.get(index);
  }

  public static final int PAGE_FIELD_NUMBER = 9;
  private com.aserto.directory.common.v2.PaginationResponse page_;
  /**
   * <pre>
   * pagination response
   * </pre>
   *
   * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
   * @return Whether the page field is set.
   */
  @java.lang.Override
  public boolean hasPage() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * pagination response
   * </pre>
   *
   * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
   * @return The page.
   */
  @java.lang.Override
  public com.aserto.directory.common.v2.PaginationResponse getPage() {
    return page_ == null ? com.aserto.directory.common.v2.PaginationResponse.getDefaultInstance() : page_;
  }
  /**
   * <pre>
   * pagination response
   * </pre>
   *
   * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
   */
  @java.lang.Override
  public com.aserto.directory.common.v2.PaginationResponseOrBuilder getPageOrBuilder() {
    return page_ == null ? com.aserto.directory.common.v2.PaginationResponse.getDefaultInstance() : page_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getResult());
    }
    for (int i = 0; i < relations_.size(); i++) {
      output.writeMessage(4, relations_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(9, getPage());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResult());
    }
    for (int i = 0; i < relations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, relations_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getPage());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aserto.directory.reader.v2.GetObjectResponse)) {
      return super.equals(obj);
    }
    com.aserto.directory.reader.v2.GetObjectResponse other = (com.aserto.directory.reader.v2.GetObjectResponse) obj;

    if (hasResult() != other.hasResult()) return false;
    if (hasResult()) {
      if (!getResult()
          .equals(other.getResult())) return false;
    }
    if (!getRelationsList()
        .equals(other.getRelationsList())) return false;
    if (hasPage() != other.hasPage()) return false;
    if (hasPage()) {
      if (!getPage()
          .equals(other.getPage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResult()) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
    }
    if (getRelationsCount() > 0) {
      hash = (37 * hash) + RELATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getRelationsList().hashCode();
    }
    if (hasPage()) {
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aserto.directory.reader.v2.GetObjectResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.directory.reader.v2.GetObjectResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.directory.reader.v2.GetObjectResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.directory.reader.v2.GetObjectResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.directory.reader.v2.GetObjectResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.directory.reader.v2.GetObjectResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.directory.reader.v2.GetObjectResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.directory.reader.v2.GetObjectResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aserto.directory.reader.v2.GetObjectResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aserto.directory.reader.v2.GetObjectResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.directory.reader.v2.GetObjectResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.directory.reader.v2.GetObjectResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aserto.directory.reader.v2.GetObjectResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aserto.directory.reader.v2.GetObjectResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aserto.directory.reader.v2.GetObjectResponse)
      com.aserto.directory.reader.v2.GetObjectResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aserto.directory.reader.v2.ReaderProto.internal_static_aserto_directory_reader_v2_GetObjectResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aserto.directory.reader.v2.ReaderProto.internal_static_aserto_directory_reader_v2_GetObjectResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aserto.directory.reader.v2.GetObjectResponse.class, com.aserto.directory.reader.v2.GetObjectResponse.Builder.class);
    }

    // Construct using com.aserto.directory.reader.v2.GetObjectResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultFieldBuilder();
        getRelationsFieldBuilder();
        getPageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      result_ = null;
      if (resultBuilder_ != null) {
        resultBuilder_.dispose();
        resultBuilder_ = null;
      }
      if (relationsBuilder_ == null) {
        relations_ = java.util.Collections.emptyList();
      } else {
        relations_ = null;
        relationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      page_ = null;
      if (pageBuilder_ != null) {
        pageBuilder_.dispose();
        pageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aserto.directory.reader.v2.ReaderProto.internal_static_aserto_directory_reader_v2_GetObjectResponse_descriptor;
    }

    @java.lang.Override
    public com.aserto.directory.reader.v2.GetObjectResponse getDefaultInstanceForType() {
      return com.aserto.directory.reader.v2.GetObjectResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.aserto.directory.reader.v2.GetObjectResponse build() {
      com.aserto.directory.reader.v2.GetObjectResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aserto.directory.reader.v2.GetObjectResponse buildPartial() {
      com.aserto.directory.reader.v2.GetObjectResponse result = new com.aserto.directory.reader.v2.GetObjectResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.aserto.directory.reader.v2.GetObjectResponse result) {
      if (relationsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          relations_ = java.util.Collections.unmodifiableList(relations_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.relations_ = relations_;
      } else {
        result.relations_ = relationsBuilder_.build();
      }
    }

    private void buildPartial0(com.aserto.directory.reader.v2.GetObjectResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.result_ = resultBuilder_ == null
            ? result_
            : resultBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.page_ = pageBuilder_ == null
            ? page_
            : pageBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aserto.directory.reader.v2.GetObjectResponse) {
        return mergeFrom((com.aserto.directory.reader.v2.GetObjectResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aserto.directory.reader.v2.GetObjectResponse other) {
      if (other == com.aserto.directory.reader.v2.GetObjectResponse.getDefaultInstance()) return this;
      if (other.hasResult()) {
        mergeResult(other.getResult());
      }
      if (relationsBuilder_ == null) {
        if (!other.relations_.isEmpty()) {
          if (relations_.isEmpty()) {
            relations_ = other.relations_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRelationsIsMutable();
            relations_.addAll(other.relations_);
          }
          onChanged();
        }
      } else {
        if (!other.relations_.isEmpty()) {
          if (relationsBuilder_.isEmpty()) {
            relationsBuilder_.dispose();
            relationsBuilder_ = null;
            relations_ = other.relations_;
            bitField0_ = (bitField0_ & ~0x00000002);
            relationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRelationsFieldBuilder() : null;
          } else {
            relationsBuilder_.addAllMessages(other.relations_);
          }
        }
      }
      if (other.hasPage()) {
        mergePage(other.getPage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getResultFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 34: {
              com.aserto.directory.common.v2.Relation m =
                  input.readMessage(
                      com.aserto.directory.common.v2.Relation.parser(),
                      extensionRegistry);
              if (relationsBuilder_ == null) {
                ensureRelationsIsMutable();
                relations_.add(m);
              } else {
                relationsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 74: {
              input.readMessage(
                  getPageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.aserto.directory.common.v2.Object result_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aserto.directory.common.v2.Object, com.aserto.directory.common.v2.Object.Builder, com.aserto.directory.common.v2.ObjectOrBuilder> resultBuilder_;
    /**
     * <pre>
     * object instance
     * </pre>
     *
     * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
     * @return Whether the result field is set.
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * object instance
     * </pre>
     *
     * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
     * @return The result.
     */
    public com.aserto.directory.common.v2.Object getResult() {
      if (resultBuilder_ == null) {
        return result_ == null ? com.aserto.directory.common.v2.Object.getDefaultInstance() : result_;
      } else {
        return resultBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * object instance
     * </pre>
     *
     * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
     */
    public Builder setResult(com.aserto.directory.common.v2.Object value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
      } else {
        resultBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * object instance
     * </pre>
     *
     * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
     */
    public Builder setResult(
        com.aserto.directory.common.v2.Object.Builder builderForValue) {
      if (resultBuilder_ == null) {
        result_ = builderForValue.build();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * object instance
     * </pre>
     *
     * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
     */
    public Builder mergeResult(com.aserto.directory.common.v2.Object value) {
      if (resultBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          result_ != null &&
          result_ != com.aserto.directory.common.v2.Object.getDefaultInstance()) {
          getResultBuilder().mergeFrom(value);
        } else {
          result_ = value;
        }
      } else {
        resultBuilder_.mergeFrom(value);
      }
      if (result_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * object instance
     * </pre>
     *
     * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
     */
    public Builder clearResult() {
      bitField0_ = (bitField0_ & ~0x00000001);
      result_ = null;
      if (resultBuilder_ != null) {
        resultBuilder_.dispose();
        resultBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * object instance
     * </pre>
     *
     * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
     */
    public com.aserto.directory.common.v2.Object.Builder getResultBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getResultFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * object instance
     * </pre>
     *
     * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
     */
    public com.aserto.directory.common.v2.ObjectOrBuilder getResultOrBuilder() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        return result_ == null ?
            com.aserto.directory.common.v2.Object.getDefaultInstance() : result_;
      }
    }
    /**
     * <pre>
     * object instance
     * </pre>
     *
     * <code>.aserto.directory.common.v2.Object result = 1 [json_name = "result"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aserto.directory.common.v2.Object, com.aserto.directory.common.v2.Object.Builder, com.aserto.directory.common.v2.ObjectOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aserto.directory.common.v2.Object, com.aserto.directory.common.v2.Object.Builder, com.aserto.directory.common.v2.ObjectOrBuilder>(
                getResult(),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }

    private java.util.List<com.aserto.directory.common.v2.Relation> relations_ =
      java.util.Collections.emptyList();
    private void ensureRelationsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        relations_ = new java.util.ArrayList<com.aserto.directory.common.v2.Relation>(relations_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aserto.directory.common.v2.Relation, com.aserto.directory.common.v2.Relation.Builder, com.aserto.directory.common.v2.RelationOrBuilder> relationsBuilder_;

    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public java.util.List<com.aserto.directory.common.v2.Relation> getRelationsList() {
      if (relationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(relations_);
      } else {
        return relationsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public int getRelationsCount() {
      if (relationsBuilder_ == null) {
        return relations_.size();
      } else {
        return relationsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public com.aserto.directory.common.v2.Relation getRelations(int index) {
      if (relationsBuilder_ == null) {
        return relations_.get(index);
      } else {
        return relationsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public Builder setRelations(
        int index, com.aserto.directory.common.v2.Relation value) {
      if (relationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRelationsIsMutable();
        relations_.set(index, value);
        onChanged();
      } else {
        relationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public Builder setRelations(
        int index, com.aserto.directory.common.v2.Relation.Builder builderForValue) {
      if (relationsBuilder_ == null) {
        ensureRelationsIsMutable();
        relations_.set(index, builderForValue.build());
        onChanged();
      } else {
        relationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public Builder addRelations(com.aserto.directory.common.v2.Relation value) {
      if (relationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRelationsIsMutable();
        relations_.add(value);
        onChanged();
      } else {
        relationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public Builder addRelations(
        int index, com.aserto.directory.common.v2.Relation value) {
      if (relationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRelationsIsMutable();
        relations_.add(index, value);
        onChanged();
      } else {
        relationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public Builder addRelations(
        com.aserto.directory.common.v2.Relation.Builder builderForValue) {
      if (relationsBuilder_ == null) {
        ensureRelationsIsMutable();
        relations_.add(builderForValue.build());
        onChanged();
      } else {
        relationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public Builder addRelations(
        int index, com.aserto.directory.common.v2.Relation.Builder builderForValue) {
      if (relationsBuilder_ == null) {
        ensureRelationsIsMutable();
        relations_.add(index, builderForValue.build());
        onChanged();
      } else {
        relationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public Builder addAllRelations(
        java.lang.Iterable<? extends com.aserto.directory.common.v2.Relation> values) {
      if (relationsBuilder_ == null) {
        ensureRelationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, relations_);
        onChanged();
      } else {
        relationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public Builder clearRelations() {
      if (relationsBuilder_ == null) {
        relations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        relationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public Builder removeRelations(int index) {
      if (relationsBuilder_ == null) {
        ensureRelationsIsMutable();
        relations_.remove(index);
        onChanged();
      } else {
        relationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public com.aserto.directory.common.v2.Relation.Builder getRelationsBuilder(
        int index) {
      return getRelationsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public com.aserto.directory.common.v2.RelationOrBuilder getRelationsOrBuilder(
        int index) {
      if (relationsBuilder_ == null) {
        return relations_.get(index);  } else {
        return relationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public java.util.List<? extends com.aserto.directory.common.v2.RelationOrBuilder> 
         getRelationsOrBuilderList() {
      if (relationsBuilder_ != null) {
        return relationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(relations_);
      }
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public com.aserto.directory.common.v2.Relation.Builder addRelationsBuilder() {
      return getRelationsFieldBuilder().addBuilder(
          com.aserto.directory.common.v2.Relation.getDefaultInstance());
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public com.aserto.directory.common.v2.Relation.Builder addRelationsBuilder(
        int index) {
      return getRelationsFieldBuilder().addBuilder(
          index, com.aserto.directory.common.v2.Relation.getDefaultInstance());
    }
    /**
     * <pre>
     * object relations
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v2.Relation relations = 4 [json_name = "relations"];</code>
     */
    public java.util.List<com.aserto.directory.common.v2.Relation.Builder> 
         getRelationsBuilderList() {
      return getRelationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aserto.directory.common.v2.Relation, com.aserto.directory.common.v2.Relation.Builder, com.aserto.directory.common.v2.RelationOrBuilder> 
        getRelationsFieldBuilder() {
      if (relationsBuilder_ == null) {
        relationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.aserto.directory.common.v2.Relation, com.aserto.directory.common.v2.Relation.Builder, com.aserto.directory.common.v2.RelationOrBuilder>(
                relations_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        relations_ = null;
      }
      return relationsBuilder_;
    }

    private com.aserto.directory.common.v2.PaginationResponse page_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aserto.directory.common.v2.PaginationResponse, com.aserto.directory.common.v2.PaginationResponse.Builder, com.aserto.directory.common.v2.PaginationResponseOrBuilder> pageBuilder_;
    /**
     * <pre>
     * pagination response
     * </pre>
     *
     * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
     * @return Whether the page field is set.
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * pagination response
     * </pre>
     *
     * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
     * @return The page.
     */
    public com.aserto.directory.common.v2.PaginationResponse getPage() {
      if (pageBuilder_ == null) {
        return page_ == null ? com.aserto.directory.common.v2.PaginationResponse.getDefaultInstance() : page_;
      } else {
        return pageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * pagination response
     * </pre>
     *
     * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
     */
    public Builder setPage(com.aserto.directory.common.v2.PaginationResponse value) {
      if (pageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        page_ = value;
      } else {
        pageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pagination response
     * </pre>
     *
     * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
     */
    public Builder setPage(
        com.aserto.directory.common.v2.PaginationResponse.Builder builderForValue) {
      if (pageBuilder_ == null) {
        page_ = builderForValue.build();
      } else {
        pageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pagination response
     * </pre>
     *
     * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
     */
    public Builder mergePage(com.aserto.directory.common.v2.PaginationResponse value) {
      if (pageBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          page_ != null &&
          page_ != com.aserto.directory.common.v2.PaginationResponse.getDefaultInstance()) {
          getPageBuilder().mergeFrom(value);
        } else {
          page_ = value;
        }
      } else {
        pageBuilder_.mergeFrom(value);
      }
      if (page_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * pagination response
     * </pre>
     *
     * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      page_ = null;
      if (pageBuilder_ != null) {
        pageBuilder_.dispose();
        pageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pagination response
     * </pre>
     *
     * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
     */
    public com.aserto.directory.common.v2.PaginationResponse.Builder getPageBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getPageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * pagination response
     * </pre>
     *
     * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
     */
    public com.aserto.directory.common.v2.PaginationResponseOrBuilder getPageOrBuilder() {
      if (pageBuilder_ != null) {
        return pageBuilder_.getMessageOrBuilder();
      } else {
        return page_ == null ?
            com.aserto.directory.common.v2.PaginationResponse.getDefaultInstance() : page_;
      }
    }
    /**
     * <pre>
     * pagination response
     * </pre>
     *
     * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aserto.directory.common.v2.PaginationResponse, com.aserto.directory.common.v2.PaginationResponse.Builder, com.aserto.directory.common.v2.PaginationResponseOrBuilder> 
        getPageFieldBuilder() {
      if (pageBuilder_ == null) {
        pageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aserto.directory.common.v2.PaginationResponse, com.aserto.directory.common.v2.PaginationResponse.Builder, com.aserto.directory.common.v2.PaginationResponseOrBuilder>(
                getPage(),
                getParentForChildren(),
                isClean());
        page_ = null;
      }
      return pageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aserto.directory.reader.v2.GetObjectResponse)
  }

  // @@protoc_insertion_point(class_scope:aserto.directory.reader.v2.GetObjectResponse)
  private static final com.aserto.directory.reader.v2.GetObjectResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aserto.directory.reader.v2.GetObjectResponse();
  }

  public static com.aserto.directory.reader.v2.GetObjectResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetObjectResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetObjectResponse>() {
    @java.lang.Override
    public GetObjectResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetObjectResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetObjectResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aserto.directory.reader.v2.GetObjectResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

