// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/directory/reader/v2/reader.proto

// Protobuf Java Version: 3.25.3
package com.aserto.directory.reader.v2;

@java.lang.Deprecated public interface GetPermissionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aserto.directory.reader.v2.GetPermissionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * array of permissions
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v2.Permission results = 1 [json_name = "results"];</code>
   */
  java.util.List<com.aserto.directory.common.v2.Permission> 
      getResultsList();
  /**
   * <pre>
   * array of permissions
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v2.Permission results = 1 [json_name = "results"];</code>
   */
  com.aserto.directory.common.v2.Permission getResults(int index);
  /**
   * <pre>
   * array of permissions
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v2.Permission results = 1 [json_name = "results"];</code>
   */
  int getResultsCount();
  /**
   * <pre>
   * array of permissions
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v2.Permission results = 1 [json_name = "results"];</code>
   */
  java.util.List<? extends com.aserto.directory.common.v2.PermissionOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <pre>
   * array of permissions
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v2.Permission results = 1 [json_name = "results"];</code>
   */
  com.aserto.directory.common.v2.PermissionOrBuilder getResultsOrBuilder(
      int index);

  /**
   * <pre>
   * pagination response
   * </pre>
   *
   * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <pre>
   * pagination response
   * </pre>
   *
   * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
   * @return The page.
   */
  com.aserto.directory.common.v2.PaginationResponse getPage();
  /**
   * <pre>
   * pagination response
   * </pre>
   *
   * <code>.aserto.directory.common.v2.PaginationResponse page = 9 [json_name = "page"];</code>
   */
  com.aserto.directory.common.v2.PaginationResponseOrBuilder getPageOrBuilder();
}
