// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/directory/exporter/v2/exporter.proto

// Protobuf Java Version: 3.25.3
package com.aserto.directory.exporter.v2;

public final class ExporterProto {
  private ExporterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aserto_directory_exporter_v2_ExportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aserto_directory_exporter_v2_ExportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aserto_directory_exporter_v2_ExportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aserto_directory_exporter_v2_ExportResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+aserto/directory/exporter/v2/exporter." +
      "proto\022\034aserto.directory.exporter.v2\032\'ase" +
      "rto/directory/common/v2/common.proto\032\037go" +
      "ogle/protobuf/timestamp.proto\"d\n\rExportR" +
      "equest\022\030\n\007options\030\001 \001(\rR\007options\0229\n\nstar" +
      "t_from\030\024 \001(\0132\032.google.protobuf.Timestamp" +
      "R\tstartFrom\"\377\002\n\016ExportResponse\022<\n\006object" +
      "\030\002 \001(\0132\".aserto.directory.common.v2.Obje" +
      "ctH\000R\006object\022I\n\013object_type\030\003 \001(\0132&.aser" +
      "to.directory.common.v2.ObjectTypeH\000R\nobj" +
      "ectType\022B\n\010relation\030\004 \001(\0132$.aserto.direc" +
      "tory.common.v2.RelationH\000R\010relation\022O\n\rr" +
      "elation_type\030\005 \001(\0132(.aserto.directory.co" +
      "mmon.v2.RelationTypeH\000R\014relationType\022H\n\n" +
      "permission\030\006 \001(\0132&.aserto.directory.comm" +
      "on.v2.PermissionH\000R\npermissionB\005\n\003msg*\307\002" +
      "\n\006Option\022\022\n\016OPTION_UNKNOWN\020\000\022 \n\034OPTION_M" +
      "ETADATA_OBJECT_TYPES\020\001\022\"\n\036OPTION_METADAT" +
      "A_RELATION_TYPES\020\002\022\037\n\033OPTION_METADATA_PE" +
      "RMISSIONS\020\004\022\023\n\017OPTION_METADATA\020\007\022\027\n\023OPTI" +
      "ON_DATA_OBJECTS\020\010\022\031\n\025OPTION_DATA_RELATIO" +
      "NS\020\020\022#\n\037OPTION_DATA_RELATIONS_WITH_KEYS\020" +
      " \022\017\n\013OPTION_DATA\020\030\022\031\n\025OPTION_DATA_WITH_K" +
      "EYS\020(\022\016\n\nOPTION_ALL\020\037\022\030\n\024OPTION_ALL_WITH" +
      "_KEYS\020/2s\n\010Exporter\022g\n\006Export\022+.aserto.d" +
      "irectory.exporter.v2.ExportRequest\032,.ase" +
      "rto.directory.exporter.v2.ExportResponse" +
      "\"\0000\001B\225\002\n com.aserto.directory.exporter.v" +
      "2B\rExporterProtoH\002P\001ZHgithub.com/aserto-" +
      "dev/go-directory/aserto/directory/export" +
      "er/v2;exporter\370\001\000\242\002\003ADE\252\002\034Aserto.Directo" +
      "ry.Exporter.V2\312\002\035Aserto\\Directory_\\Expor" +
      "ter\\V2\342\002)Aserto\\Directory_\\Exporter\\V2\\G" +
      "PBMetadata\352\002\037Aserto::Directory::Exporter" +
      "::V2b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.aserto.directory.common.v2.CommonProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_aserto_directory_exporter_v2_ExportRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aserto_directory_exporter_v2_ExportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aserto_directory_exporter_v2_ExportRequest_descriptor,
        new java.lang.String[] { "Options", "StartFrom", });
    internal_static_aserto_directory_exporter_v2_ExportResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aserto_directory_exporter_v2_ExportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aserto_directory_exporter_v2_ExportResponse_descriptor,
        new java.lang.String[] { "Object", "ObjectType", "Relation", "RelationType", "Permission", "Msg", });
    com.aserto.directory.common.v2.CommonProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
