// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buf/validate/validate.proto

// Protobuf Java Version: 3.25.2
package com.buf.validate;

/**
 * <pre>
 * MessageConstraints represents validation rules that are applied to the entire message.
 * It includes disabling options and a list of Constraint messages representing Common Expression Language (CEL) validation rules.
 * </pre>
 *
 * Protobuf type {@code buf.validate.MessageConstraints}
 */
public final class MessageConstraints extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:buf.validate.MessageConstraints)
    MessageConstraintsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageConstraints.newBuilder() to construct.
  private MessageConstraints(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageConstraints() {
    cel_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageConstraints();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.buf.validate.ValidateProto.internal_static_buf_validate_MessageConstraints_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.buf.validate.ValidateProto.internal_static_buf_validate_MessageConstraints_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.buf.validate.MessageConstraints.class, com.buf.validate.MessageConstraints.Builder.class);
  }

  private int bitField0_;
  public static final int DISABLED_FIELD_NUMBER = 1;
  private boolean disabled_ = false;
  /**
   * <pre>
   * `disabled` is a boolean flag that, when set to true, nullifies any validation rules for this message.
   * This includes any fields within the message that would otherwise support validation.
   *
   * ```proto
   * message MyMessage {
   *   // validation will be bypassed for this message
   *   option (buf.validate.message).disabled = true;
   * }
   * ```
   * </pre>
   *
   * <code>optional bool disabled = 1 [json_name = "disabled"];</code>
   * @return Whether the disabled field is set.
   */
  @java.lang.Override
  public boolean hasDisabled() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * `disabled` is a boolean flag that, when set to true, nullifies any validation rules for this message.
   * This includes any fields within the message that would otherwise support validation.
   *
   * ```proto
   * message MyMessage {
   *   // validation will be bypassed for this message
   *   option (buf.validate.message).disabled = true;
   * }
   * ```
   * </pre>
   *
   * <code>optional bool disabled = 1 [json_name = "disabled"];</code>
   * @return The disabled.
   */
  @java.lang.Override
  public boolean getDisabled() {
    return disabled_;
  }

  public static final int CEL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.buf.validate.Constraint> cel_;
  /**
   * <pre>
   * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
   * These constraints are written in Common Expression Language (CEL) syntax. For more information on
   * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
   *
   *
   * ```proto
   * message MyMessage {
   *   // The field `foo` must be greater than 42.
   *   option (buf.validate.message).cel = {
   *     id: "my_message.value",
   *     message: "value must be greater than 42",
   *     expression: "this.foo &gt; 42",
   *   };
   *   optional int32 foo = 1;
   * }
   * ```
   * </pre>
   *
   * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
   */
  @java.lang.Override
  public java.util.List<com.buf.validate.Constraint> getCelList() {
    return cel_;
  }
  /**
   * <pre>
   * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
   * These constraints are written in Common Expression Language (CEL) syntax. For more information on
   * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
   *
   *
   * ```proto
   * message MyMessage {
   *   // The field `foo` must be greater than 42.
   *   option (buf.validate.message).cel = {
   *     id: "my_message.value",
   *     message: "value must be greater than 42",
   *     expression: "this.foo &gt; 42",
   *   };
   *   optional int32 foo = 1;
   * }
   * ```
   * </pre>
   *
   * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.buf.validate.ConstraintOrBuilder> 
      getCelOrBuilderList() {
    return cel_;
  }
  /**
   * <pre>
   * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
   * These constraints are written in Common Expression Language (CEL) syntax. For more information on
   * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
   *
   *
   * ```proto
   * message MyMessage {
   *   // The field `foo` must be greater than 42.
   *   option (buf.validate.message).cel = {
   *     id: "my_message.value",
   *     message: "value must be greater than 42",
   *     expression: "this.foo &gt; 42",
   *   };
   *   optional int32 foo = 1;
   * }
   * ```
   * </pre>
   *
   * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
   */
  @java.lang.Override
  public int getCelCount() {
    return cel_.size();
  }
  /**
   * <pre>
   * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
   * These constraints are written in Common Expression Language (CEL) syntax. For more information on
   * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
   *
   *
   * ```proto
   * message MyMessage {
   *   // The field `foo` must be greater than 42.
   *   option (buf.validate.message).cel = {
   *     id: "my_message.value",
   *     message: "value must be greater than 42",
   *     expression: "this.foo &gt; 42",
   *   };
   *   optional int32 foo = 1;
   * }
   * ```
   * </pre>
   *
   * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
   */
  @java.lang.Override
  public com.buf.validate.Constraint getCel(int index) {
    return cel_.get(index);
  }
  /**
   * <pre>
   * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
   * These constraints are written in Common Expression Language (CEL) syntax. For more information on
   * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
   *
   *
   * ```proto
   * message MyMessage {
   *   // The field `foo` must be greater than 42.
   *   option (buf.validate.message).cel = {
   *     id: "my_message.value",
   *     message: "value must be greater than 42",
   *     expression: "this.foo &gt; 42",
   *   };
   *   optional int32 foo = 1;
   * }
   * ```
   * </pre>
   *
   * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
   */
  @java.lang.Override
  public com.buf.validate.ConstraintOrBuilder getCelOrBuilder(
      int index) {
    return cel_.get(index);
  }

  public static com.buf.validate.MessageConstraints parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.buf.validate.MessageConstraints parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.buf.validate.MessageConstraints parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.buf.validate.MessageConstraints parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.buf.validate.MessageConstraints parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.buf.validate.MessageConstraints parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.buf.validate.MessageConstraints parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.buf.validate.MessageConstraints parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.buf.validate.MessageConstraints parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.buf.validate.MessageConstraints parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.buf.validate.MessageConstraints parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.buf.validate.MessageConstraints parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.buf.validate.MessageConstraints prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MessageConstraints represents validation rules that are applied to the entire message.
   * It includes disabling options and a list of Constraint messages representing Common Expression Language (CEL) validation rules.
   * </pre>
   *
   * Protobuf type {@code buf.validate.MessageConstraints}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:buf.validate.MessageConstraints)
      com.buf.validate.MessageConstraintsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.buf.validate.ValidateProto.internal_static_buf_validate_MessageConstraints_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.buf.validate.ValidateProto.internal_static_buf_validate_MessageConstraints_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.buf.validate.MessageConstraints.class, com.buf.validate.MessageConstraints.Builder.class);
    }

    // Construct using com.buf.validate.MessageConstraints.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      disabled_ = false;
      if (celBuilder_ == null) {
        cel_ = java.util.Collections.emptyList();
      } else {
        cel_ = null;
        celBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.buf.validate.ValidateProto.internal_static_buf_validate_MessageConstraints_descriptor;
    }

    @java.lang.Override
    public com.buf.validate.MessageConstraints getDefaultInstanceForType() {
      return com.buf.validate.MessageConstraints.getDefaultInstance();
    }

    @java.lang.Override
    public com.buf.validate.MessageConstraints build() {
      com.buf.validate.MessageConstraints result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.buf.validate.MessageConstraints buildPartial() {
      com.buf.validate.MessageConstraints result = new com.buf.validate.MessageConstraints(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.buf.validate.MessageConstraints result) {
      if (celBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          cel_ = java.util.Collections.unmodifiableList(cel_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.cel_ = cel_;
      } else {
        result.cel_ = celBuilder_.build();
      }
    }

    private void buildPartial0(com.buf.validate.MessageConstraints result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.disabled_ = disabled_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private boolean disabled_ ;
    /**
     * <pre>
     * `disabled` is a boolean flag that, when set to true, nullifies any validation rules for this message.
     * This includes any fields within the message that would otherwise support validation.
     *
     * ```proto
     * message MyMessage {
     *   // validation will be bypassed for this message
     *   option (buf.validate.message).disabled = true;
     * }
     * ```
     * </pre>
     *
     * <code>optional bool disabled = 1 [json_name = "disabled"];</code>
     * @return Whether the disabled field is set.
     */
    @java.lang.Override
    public boolean hasDisabled() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * `disabled` is a boolean flag that, when set to true, nullifies any validation rules for this message.
     * This includes any fields within the message that would otherwise support validation.
     *
     * ```proto
     * message MyMessage {
     *   // validation will be bypassed for this message
     *   option (buf.validate.message).disabled = true;
     * }
     * ```
     * </pre>
     *
     * <code>optional bool disabled = 1 [json_name = "disabled"];</code>
     * @return The disabled.
     */
    @java.lang.Override
    public boolean getDisabled() {
      return disabled_;
    }
    /**
     * <pre>
     * `disabled` is a boolean flag that, when set to true, nullifies any validation rules for this message.
     * This includes any fields within the message that would otherwise support validation.
     *
     * ```proto
     * message MyMessage {
     *   // validation will be bypassed for this message
     *   option (buf.validate.message).disabled = true;
     * }
     * ```
     * </pre>
     *
     * <code>optional bool disabled = 1 [json_name = "disabled"];</code>
     * @param value The disabled to set.
     * @return This builder for chaining.
     */
    public Builder setDisabled(boolean value) {

      disabled_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * `disabled` is a boolean flag that, when set to true, nullifies any validation rules for this message.
     * This includes any fields within the message that would otherwise support validation.
     *
     * ```proto
     * message MyMessage {
     *   // validation will be bypassed for this message
     *   option (buf.validate.message).disabled = true;
     * }
     * ```
     * </pre>
     *
     * <code>optional bool disabled = 1 [json_name = "disabled"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDisabled() {
      bitField0_ = (bitField0_ & ~0x00000001);
      disabled_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.buf.validate.Constraint> cel_ =
      java.util.Collections.emptyList();
    private void ensureCelIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        cel_ = new java.util.ArrayList<com.buf.validate.Constraint>(cel_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.buf.validate.Constraint, com.buf.validate.Constraint.Builder, com.buf.validate.ConstraintOrBuilder> celBuilder_;

    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public java.util.List<com.buf.validate.Constraint> getCelList() {
      if (celBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cel_);
      } else {
        return celBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public int getCelCount() {
      if (celBuilder_ == null) {
        return cel_.size();
      } else {
        return celBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public com.buf.validate.Constraint getCel(int index) {
      if (celBuilder_ == null) {
        return cel_.get(index);
      } else {
        return celBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public Builder setCel(
        int index, com.buf.validate.Constraint value) {
      if (celBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCelIsMutable();
        cel_.set(index, value);
        onChanged();
      } else {
        celBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public Builder setCel(
        int index, com.buf.validate.Constraint.Builder builderForValue) {
      if (celBuilder_ == null) {
        ensureCelIsMutable();
        cel_.set(index, builderForValue.build());
        onChanged();
      } else {
        celBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public Builder addCel(com.buf.validate.Constraint value) {
      if (celBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCelIsMutable();
        cel_.add(value);
        onChanged();
      } else {
        celBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public Builder addCel(
        int index, com.buf.validate.Constraint value) {
      if (celBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCelIsMutable();
        cel_.add(index, value);
        onChanged();
      } else {
        celBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public Builder addCel(
        com.buf.validate.Constraint.Builder builderForValue) {
      if (celBuilder_ == null) {
        ensureCelIsMutable();
        cel_.add(builderForValue.build());
        onChanged();
      } else {
        celBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public Builder addCel(
        int index, com.buf.validate.Constraint.Builder builderForValue) {
      if (celBuilder_ == null) {
        ensureCelIsMutable();
        cel_.add(index, builderForValue.build());
        onChanged();
      } else {
        celBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public Builder addAllCel(
        java.lang.Iterable<? extends com.buf.validate.Constraint> values) {
      if (celBuilder_ == null) {
        ensureCelIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cel_);
        onChanged();
      } else {
        celBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public Builder clearCel() {
      if (celBuilder_ == null) {
        cel_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        celBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public Builder removeCel(int index) {
      if (celBuilder_ == null) {
        ensureCelIsMutable();
        cel_.remove(index);
        onChanged();
      } else {
        celBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public com.buf.validate.Constraint.Builder getCelBuilder(
        int index) {
      return getCelFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public com.buf.validate.ConstraintOrBuilder getCelOrBuilder(
        int index) {
      if (celBuilder_ == null) {
        return cel_.get(index);  } else {
        return celBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public java.util.List<? extends com.buf.validate.ConstraintOrBuilder> 
         getCelOrBuilderList() {
      if (celBuilder_ != null) {
        return celBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cel_);
      }
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public com.buf.validate.Constraint.Builder addCelBuilder() {
      return getCelFieldBuilder().addBuilder(
          com.buf.validate.Constraint.getDefaultInstance());
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public com.buf.validate.Constraint.Builder addCelBuilder(
        int index) {
      return getCelFieldBuilder().addBuilder(
          index, com.buf.validate.Constraint.getDefaultInstance());
    }
    /**
     * <pre>
     * `cel` is a repeated field of type Constraint. Each Constraint specifies a validation rule to be applied to this message.
     * These constraints are written in Common Expression Language (CEL) syntax. For more information on
     * CEL, [see our documentation](https://github.com/bufbuild/protovalidate/blob/main/docs/cel.md).
     *
     *
     * ```proto
     * message MyMessage {
     *   // The field `foo` must be greater than 42.
     *   option (buf.validate.message).cel = {
     *     id: "my_message.value",
     *     message: "value must be greater than 42",
     *     expression: "this.foo &gt; 42",
     *   };
     *   optional int32 foo = 1;
     * }
     * ```
     * </pre>
     *
     * <code>repeated .buf.validate.Constraint cel = 3 [json_name = "cel"];</code>
     */
    public java.util.List<com.buf.validate.Constraint.Builder> 
         getCelBuilderList() {
      return getCelFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.buf.validate.Constraint, com.buf.validate.Constraint.Builder, com.buf.validate.ConstraintOrBuilder> 
        getCelFieldBuilder() {
      if (celBuilder_ == null) {
        celBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.buf.validate.Constraint, com.buf.validate.Constraint.Builder, com.buf.validate.ConstraintOrBuilder>(
                cel_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        cel_ = null;
      }
      return celBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:buf.validate.MessageConstraints)
  }

  // @@protoc_insertion_point(class_scope:buf.validate.MessageConstraints)
  private static final com.buf.validate.MessageConstraints DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.buf.validate.MessageConstraints();
  }

  public static com.buf.validate.MessageConstraints getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageConstraints>
      PARSER = new com.google.protobuf.AbstractParser<MessageConstraints>() {
    @java.lang.Override
    public MessageConstraints parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessageConstraints> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageConstraints> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.buf.validate.MessageConstraints getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

