// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/directory/writer/v2/writer.proto

package com.aserto.directory.writer.v2;

public interface SetRelationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aserto.directory.writer.v2.SetRelationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.aserto.directory.common.v2.Relation relation = 1 [json_name = "relation"];</code>
   * @return Whether the relation field is set.
   */
  boolean hasRelation();
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.aserto.directory.common.v2.Relation relation = 1 [json_name = "relation"];</code>
   * @return The relation.
   */
  com.aserto.directory.common.v2.Relation getRelation();
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.aserto.directory.common.v2.Relation relation = 1 [json_name = "relation"];</code>
   */
  com.aserto.directory.common.v2.RelationOrBuilder getRelationOrBuilder();
}
