// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/directory/writer/v2/writer.proto

package com.aserto.directory.writer.v2;

public interface SetObjectTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aserto.directory.writer.v2.SetObjectTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.aserto.directory.common.v2.ObjectType object_type = 1 [json_name = "objectType"];</code>
   * @return Whether the objectType field is set.
   */
  boolean hasObjectType();
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.aserto.directory.common.v2.ObjectType object_type = 1 [json_name = "objectType"];</code>
   * @return The objectType.
   */
  com.aserto.directory.common.v2.ObjectType getObjectType();
  /**
   * <pre>
   * 
   * </pre>
   *
   * <code>.aserto.directory.common.v2.ObjectType object_type = 1 [json_name = "objectType"];</code>
   */
  com.aserto.directory.common.v2.ObjectTypeOrBuilder getObjectTypeOrBuilder();
}
