// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/directory/assertion/v3/assertion.proto

// Protobuf Java Version: 3.25.3
package com.aserto.directory.assertion.v3;

public interface ListAssertionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aserto.directory.assertion.v3.ListAssertionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .aserto.directory.assertion.v3.Assert results = 1 [json_name = "results"];</code>
   */
  java.util.List<com.aserto.directory.assertion.v3.Assert> 
      getResultsList();
  /**
   * <code>repeated .aserto.directory.assertion.v3.Assert results = 1 [json_name = "results"];</code>
   */
  com.aserto.directory.assertion.v3.Assert getResults(int index);
  /**
   * <code>repeated .aserto.directory.assertion.v3.Assert results = 1 [json_name = "results"];</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .aserto.directory.assertion.v3.Assert results = 1 [json_name = "results"];</code>
   */
  java.util.List<? extends com.aserto.directory.assertion.v3.AssertOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .aserto.directory.assertion.v3.Assert results = 1 [json_name = "results"];</code>
   */
  com.aserto.directory.assertion.v3.AssertOrBuilder getResultsOrBuilder(
      int index);

  /**
   * <code>.aserto.directory.common.v3.PaginationResponse page = 2 [json_name = "page"];</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>.aserto.directory.common.v3.PaginationResponse page = 2 [json_name = "page"];</code>
   * @return The page.
   */
  com.aserto.directory.common.v3.PaginationResponse getPage();
  /**
   * <code>.aserto.directory.common.v3.PaginationResponse page = 2 [json_name = "page"];</code>
   */
  com.aserto.directory.common.v3.PaginationResponseOrBuilder getPageOrBuilder();
}
