// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/directory/writer/v3/writer.proto

// Protobuf Java Version: 3.25.1
package com.aserto.directory.writer.v3;

/**
 * Protobuf type {@code aserto.directory.writer.v3.SetRelationRequest}
 */
public final class SetRelationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aserto.directory.writer.v3.SetRelationRequest)
    SetRelationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetRelationRequest.newBuilder() to construct.
  private SetRelationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetRelationRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SetRelationRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aserto.directory.writer.v3.WriterProto.internal_static_aserto_directory_writer_v3_SetRelationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aserto.directory.writer.v3.WriterProto.internal_static_aserto_directory_writer_v3_SetRelationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aserto.directory.writer.v3.SetRelationRequest.class, com.aserto.directory.writer.v3.SetRelationRequest.Builder.class);
  }

  private int bitField0_;
  public static final int RELATION_FIELD_NUMBER = 1;
  private com.aserto.directory.common.v3.Relation relation_;
  /**
   * <pre>
   * relation instance
   * </pre>
   *
   * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
   * @return Whether the relation field is set.
   */
  @java.lang.Override
  public boolean hasRelation() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * relation instance
   * </pre>
   *
   * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
   * @return The relation.
   */
  @java.lang.Override
  public com.aserto.directory.common.v3.Relation getRelation() {
    return relation_ == null ? com.aserto.directory.common.v3.Relation.getDefaultInstance() : relation_;
  }
  /**
   * <pre>
   * relation instance
   * </pre>
   *
   * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.aserto.directory.common.v3.RelationOrBuilder getRelationOrBuilder() {
    return relation_ == null ? com.aserto.directory.common.v3.Relation.getDefaultInstance() : relation_;
  }

  public static com.aserto.directory.writer.v3.SetRelationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.directory.writer.v3.SetRelationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.directory.writer.v3.SetRelationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.directory.writer.v3.SetRelationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.directory.writer.v3.SetRelationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.directory.writer.v3.SetRelationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.directory.writer.v3.SetRelationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.directory.writer.v3.SetRelationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aserto.directory.writer.v3.SetRelationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aserto.directory.writer.v3.SetRelationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.directory.writer.v3.SetRelationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.directory.writer.v3.SetRelationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aserto.directory.writer.v3.SetRelationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aserto.directory.writer.v3.SetRelationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aserto.directory.writer.v3.SetRelationRequest)
      com.aserto.directory.writer.v3.SetRelationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aserto.directory.writer.v3.WriterProto.internal_static_aserto_directory_writer_v3_SetRelationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aserto.directory.writer.v3.WriterProto.internal_static_aserto_directory_writer_v3_SetRelationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aserto.directory.writer.v3.SetRelationRequest.class, com.aserto.directory.writer.v3.SetRelationRequest.Builder.class);
    }

    // Construct using com.aserto.directory.writer.v3.SetRelationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRelationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      relation_ = null;
      if (relationBuilder_ != null) {
        relationBuilder_.dispose();
        relationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aserto.directory.writer.v3.WriterProto.internal_static_aserto_directory_writer_v3_SetRelationRequest_descriptor;
    }

    @java.lang.Override
    public com.aserto.directory.writer.v3.SetRelationRequest getDefaultInstanceForType() {
      return com.aserto.directory.writer.v3.SetRelationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.aserto.directory.writer.v3.SetRelationRequest build() {
      com.aserto.directory.writer.v3.SetRelationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aserto.directory.writer.v3.SetRelationRequest buildPartial() {
      com.aserto.directory.writer.v3.SetRelationRequest result = new com.aserto.directory.writer.v3.SetRelationRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aserto.directory.writer.v3.SetRelationRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.relation_ = relationBuilder_ == null
            ? relation_
            : relationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private com.aserto.directory.common.v3.Relation relation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aserto.directory.common.v3.Relation, com.aserto.directory.common.v3.Relation.Builder, com.aserto.directory.common.v3.RelationOrBuilder> relationBuilder_;
    /**
     * <pre>
     * relation instance
     * </pre>
     *
     * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
     * @return Whether the relation field is set.
     */
    public boolean hasRelation() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * relation instance
     * </pre>
     *
     * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
     * @return The relation.
     */
    public com.aserto.directory.common.v3.Relation getRelation() {
      if (relationBuilder_ == null) {
        return relation_ == null ? com.aserto.directory.common.v3.Relation.getDefaultInstance() : relation_;
      } else {
        return relationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * relation instance
     * </pre>
     *
     * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
     */
    public Builder setRelation(com.aserto.directory.common.v3.Relation value) {
      if (relationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        relation_ = value;
      } else {
        relationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * relation instance
     * </pre>
     *
     * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
     */
    public Builder setRelation(
        com.aserto.directory.common.v3.Relation.Builder builderForValue) {
      if (relationBuilder_ == null) {
        relation_ = builderForValue.build();
      } else {
        relationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * relation instance
     * </pre>
     *
     * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeRelation(com.aserto.directory.common.v3.Relation value) {
      if (relationBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          relation_ != null &&
          relation_ != com.aserto.directory.common.v3.Relation.getDefaultInstance()) {
          getRelationBuilder().mergeFrom(value);
        } else {
          relation_ = value;
        }
      } else {
        relationBuilder_.mergeFrom(value);
      }
      if (relation_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * relation instance
     * </pre>
     *
     * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
     */
    public Builder clearRelation() {
      bitField0_ = (bitField0_ & ~0x00000001);
      relation_ = null;
      if (relationBuilder_ != null) {
        relationBuilder_.dispose();
        relationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * relation instance
     * </pre>
     *
     * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
     */
    public com.aserto.directory.common.v3.Relation.Builder getRelationBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getRelationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * relation instance
     * </pre>
     *
     * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
     */
    public com.aserto.directory.common.v3.RelationOrBuilder getRelationOrBuilder() {
      if (relationBuilder_ != null) {
        return relationBuilder_.getMessageOrBuilder();
      } else {
        return relation_ == null ?
            com.aserto.directory.common.v3.Relation.getDefaultInstance() : relation_;
      }
    }
    /**
     * <pre>
     * relation instance
     * </pre>
     *
     * <code>.aserto.directory.common.v3.Relation relation = 1 [json_name = "relation", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aserto.directory.common.v3.Relation, com.aserto.directory.common.v3.Relation.Builder, com.aserto.directory.common.v3.RelationOrBuilder> 
        getRelationFieldBuilder() {
      if (relationBuilder_ == null) {
        relationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aserto.directory.common.v3.Relation, com.aserto.directory.common.v3.Relation.Builder, com.aserto.directory.common.v3.RelationOrBuilder>(
                getRelation(),
                getParentForChildren(),
                isClean());
        relation_ = null;
      }
      return relationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aserto.directory.writer.v3.SetRelationRequest)
  }

  // @@protoc_insertion_point(class_scope:aserto.directory.writer.v3.SetRelationRequest)
  private static final com.aserto.directory.writer.v3.SetRelationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aserto.directory.writer.v3.SetRelationRequest();
  }

  public static com.aserto.directory.writer.v3.SetRelationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetRelationRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetRelationRequest>() {
    @java.lang.Override
    public SetRelationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SetRelationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetRelationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aserto.directory.writer.v3.SetRelationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

