// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/directory/common/v2/common.proto

// Protobuf Java Version: 3.25.0
package com.aserto.directory.common.v2;

public interface RelationIdentifierOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aserto.directory.common.v2.RelationIdentifier)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * subject identifier
   * </pre>
   *
   * <code>.aserto.directory.common.v2.ObjectIdentifier subject = 1 [json_name = "subject"];</code>
   * @return Whether the subject field is set.
   */
  boolean hasSubject();
  /**
   * <pre>
   * subject identifier
   * </pre>
   *
   * <code>.aserto.directory.common.v2.ObjectIdentifier subject = 1 [json_name = "subject"];</code>
   * @return The subject.
   */
  com.aserto.directory.common.v2.ObjectIdentifier getSubject();
  /**
   * <pre>
   * subject identifier
   * </pre>
   *
   * <code>.aserto.directory.common.v2.ObjectIdentifier subject = 1 [json_name = "subject"];</code>
   */
  com.aserto.directory.common.v2.ObjectIdentifierOrBuilder getSubjectOrBuilder();

  /**
   * <pre>
   * relation identifier
   * </pre>
   *
   * <code>.aserto.directory.common.v2.RelationTypeIdentifier relation = 2 [json_name = "relation"];</code>
   * @return Whether the relation field is set.
   */
  boolean hasRelation();
  /**
   * <pre>
   * relation identifier
   * </pre>
   *
   * <code>.aserto.directory.common.v2.RelationTypeIdentifier relation = 2 [json_name = "relation"];</code>
   * @return The relation.
   */
  com.aserto.directory.common.v2.RelationTypeIdentifier getRelation();
  /**
   * <pre>
   * relation identifier
   * </pre>
   *
   * <code>.aserto.directory.common.v2.RelationTypeIdentifier relation = 2 [json_name = "relation"];</code>
   */
  com.aserto.directory.common.v2.RelationTypeIdentifierOrBuilder getRelationOrBuilder();

  /**
   * <pre>
   * object identifier
   * </pre>
   *
   * <code>.aserto.directory.common.v2.ObjectIdentifier object = 3 [json_name = "object"];</code>
   * @return Whether the object field is set.
   */
  boolean hasObject();
  /**
   * <pre>
   * object identifier
   * </pre>
   *
   * <code>.aserto.directory.common.v2.ObjectIdentifier object = 3 [json_name = "object"];</code>
   * @return The object.
   */
  com.aserto.directory.common.v2.ObjectIdentifier getObject();
  /**
   * <pre>
   * object identifier
   * </pre>
   *
   * <code>.aserto.directory.common.v2.ObjectIdentifier object = 3 [json_name = "object"];</code>
   */
  com.aserto.directory.common.v2.ObjectIdentifierOrBuilder getObjectOrBuilder();
}
