// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aserto/directory/reader/v3/reader.proto

// Protobuf Java Version: 3.25.2
package com.aserto.directory.reader.v3;

/**
 * Protobuf type {@code aserto.directory.reader.v3.GetGraphResponse}
 */
public final class GetGraphResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aserto.directory.reader.v3.GetGraphResponse)
    GetGraphResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetGraphResponse.newBuilder() to construct.
  private GetGraphResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetGraphResponse() {
    results_ = java.util.Collections.emptyList();
    trace_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetGraphResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aserto.directory.reader.v3.ReaderProto.internal_static_aserto_directory_reader_v3_GetGraphResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aserto.directory.reader.v3.ReaderProto.internal_static_aserto_directory_reader_v3_GetGraphResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aserto.directory.reader.v3.GetGraphResponse.class, com.aserto.directory.reader.v3.GetGraphResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RESULTS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.aserto.directory.common.v3.ObjectIdentifier> results_;
  /**
   * <pre>
   * matching object identifiers
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
   */
  @java.lang.Override
  public java.util.List<com.aserto.directory.common.v3.ObjectIdentifier> getResultsList() {
    return results_;
  }
  /**
   * <pre>
   * matching object identifiers
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.aserto.directory.common.v3.ObjectIdentifierOrBuilder> 
      getResultsOrBuilderList() {
    return results_;
  }
  /**
   * <pre>
   * matching object identifiers
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
   */
  @java.lang.Override
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <pre>
   * matching object identifiers
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
   */
  @java.lang.Override
  public com.aserto.directory.common.v3.ObjectIdentifier getResults(int index) {
    return results_.get(index);
  }
  /**
   * <pre>
   * matching object identifiers
   * </pre>
   *
   * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
   */
  @java.lang.Override
  public com.aserto.directory.common.v3.ObjectIdentifierOrBuilder getResultsOrBuilder(
      int index) {
    return results_.get(index);
  }

  public static final int EXPLANATION_FIELD_NUMBER = 3;
  private com.google.protobuf.Struct explanation_;
  /**
   * <pre>
   * explanation of results
   * </pre>
   *
   * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
   * @return Whether the explanation field is set.
   */
  @java.lang.Override
  public boolean hasExplanation() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * explanation of results
   * </pre>
   *
   * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
   * @return The explanation.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getExplanation() {
    return explanation_ == null ? com.google.protobuf.Struct.getDefaultInstance() : explanation_;
  }
  /**
   * <pre>
   * explanation of results
   * </pre>
   *
   * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getExplanationOrBuilder() {
    return explanation_ == null ? com.google.protobuf.Struct.getDefaultInstance() : explanation_;
  }

  public static final int TRACE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList trace_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * trace information
   * </pre>
   *
   * <code>repeated string trace = 4 [json_name = "trace"];</code>
   * @return A list containing the trace.
   */
  public com.google.protobuf.ProtocolStringList
      getTraceList() {
    return trace_;
  }
  /**
   * <pre>
   * trace information
   * </pre>
   *
   * <code>repeated string trace = 4 [json_name = "trace"];</code>
   * @return The count of trace.
   */
  public int getTraceCount() {
    return trace_.size();
  }
  /**
   * <pre>
   * trace information
   * </pre>
   *
   * <code>repeated string trace = 4 [json_name = "trace"];</code>
   * @param index The index of the element to return.
   * @return The trace at the given index.
   */
  public java.lang.String getTrace(int index) {
    return trace_.get(index);
  }
  /**
   * <pre>
   * trace information
   * </pre>
   *
   * <code>repeated string trace = 4 [json_name = "trace"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the trace at the given index.
   */
  public com.google.protobuf.ByteString
      getTraceBytes(int index) {
    return trace_.getByteString(index);
  }

  public static com.aserto.directory.reader.v3.GetGraphResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.directory.reader.v3.GetGraphResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.directory.reader.v3.GetGraphResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.directory.reader.v3.GetGraphResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.directory.reader.v3.GetGraphResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aserto.directory.reader.v3.GetGraphResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aserto.directory.reader.v3.GetGraphResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.directory.reader.v3.GetGraphResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aserto.directory.reader.v3.GetGraphResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aserto.directory.reader.v3.GetGraphResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aserto.directory.reader.v3.GetGraphResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aserto.directory.reader.v3.GetGraphResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aserto.directory.reader.v3.GetGraphResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aserto.directory.reader.v3.GetGraphResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aserto.directory.reader.v3.GetGraphResponse)
      com.aserto.directory.reader.v3.GetGraphResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aserto.directory.reader.v3.ReaderProto.internal_static_aserto_directory_reader_v3_GetGraphResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aserto.directory.reader.v3.ReaderProto.internal_static_aserto_directory_reader_v3_GetGraphResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aserto.directory.reader.v3.GetGraphResponse.class, com.aserto.directory.reader.v3.GetGraphResponse.Builder.class);
    }

    // Construct using com.aserto.directory.reader.v3.GetGraphResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultsFieldBuilder();
        getExplanationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
      } else {
        results_ = null;
        resultsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      explanation_ = null;
      if (explanationBuilder_ != null) {
        explanationBuilder_.dispose();
        explanationBuilder_ = null;
      }
      trace_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aserto.directory.reader.v3.ReaderProto.internal_static_aserto_directory_reader_v3_GetGraphResponse_descriptor;
    }

    @java.lang.Override
    public com.aserto.directory.reader.v3.GetGraphResponse getDefaultInstanceForType() {
      return com.aserto.directory.reader.v3.GetGraphResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.aserto.directory.reader.v3.GetGraphResponse build() {
      com.aserto.directory.reader.v3.GetGraphResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aserto.directory.reader.v3.GetGraphResponse buildPartial() {
      com.aserto.directory.reader.v3.GetGraphResponse result = new com.aserto.directory.reader.v3.GetGraphResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.aserto.directory.reader.v3.GetGraphResponse result) {
      if (resultsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.results_ = results_;
      } else {
        result.results_ = resultsBuilder_.build();
      }
    }

    private void buildPartial0(com.aserto.directory.reader.v3.GetGraphResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.explanation_ = explanationBuilder_ == null
            ? explanation_
            : explanationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        trace_.makeImmutable();
        result.trace_ = trace_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private java.util.List<com.aserto.directory.common.v3.ObjectIdentifier> results_ =
      java.util.Collections.emptyList();
    private void ensureResultsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        results_ = new java.util.ArrayList<com.aserto.directory.common.v3.ObjectIdentifier>(results_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aserto.directory.common.v3.ObjectIdentifier, com.aserto.directory.common.v3.ObjectIdentifier.Builder, com.aserto.directory.common.v3.ObjectIdentifierOrBuilder> resultsBuilder_;

    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public java.util.List<com.aserto.directory.common.v3.ObjectIdentifier> getResultsList() {
      if (resultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(results_);
      } else {
        return resultsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public int getResultsCount() {
      if (resultsBuilder_ == null) {
        return results_.size();
      } else {
        return resultsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public com.aserto.directory.common.v3.ObjectIdentifier getResults(int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);
      } else {
        return resultsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public Builder setResults(
        int index, com.aserto.directory.common.v3.ObjectIdentifier value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public Builder setResults(
        int index, com.aserto.directory.common.v3.ObjectIdentifier.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public Builder addResults(com.aserto.directory.common.v3.ObjectIdentifier value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public Builder addResults(
        int index, com.aserto.directory.common.v3.ObjectIdentifier value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(index, value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public Builder addResults(
        com.aserto.directory.common.v3.ObjectIdentifier.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public Builder addResults(
        int index, com.aserto.directory.common.v3.ObjectIdentifier.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public Builder addAllResults(
        java.lang.Iterable<? extends com.aserto.directory.common.v3.ObjectIdentifier> values) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
      } else {
        resultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public Builder clearResults() {
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public Builder removeResults(int index) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.remove(index);
        onChanged();
      } else {
        resultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public com.aserto.directory.common.v3.ObjectIdentifier.Builder getResultsBuilder(
        int index) {
      return getResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public com.aserto.directory.common.v3.ObjectIdentifierOrBuilder getResultsOrBuilder(
        int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);  } else {
        return resultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public java.util.List<? extends com.aserto.directory.common.v3.ObjectIdentifierOrBuilder> 
         getResultsOrBuilderList() {
      if (resultsBuilder_ != null) {
        return resultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(results_);
      }
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public com.aserto.directory.common.v3.ObjectIdentifier.Builder addResultsBuilder() {
      return getResultsFieldBuilder().addBuilder(
          com.aserto.directory.common.v3.ObjectIdentifier.getDefaultInstance());
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public com.aserto.directory.common.v3.ObjectIdentifier.Builder addResultsBuilder(
        int index) {
      return getResultsFieldBuilder().addBuilder(
          index, com.aserto.directory.common.v3.ObjectIdentifier.getDefaultInstance());
    }
    /**
     * <pre>
     * matching object identifiers
     * </pre>
     *
     * <code>repeated .aserto.directory.common.v3.ObjectIdentifier results = 2 [json_name = "results"];</code>
     */
    public java.util.List<com.aserto.directory.common.v3.ObjectIdentifier.Builder> 
         getResultsBuilderList() {
      return getResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aserto.directory.common.v3.ObjectIdentifier, com.aserto.directory.common.v3.ObjectIdentifier.Builder, com.aserto.directory.common.v3.ObjectIdentifierOrBuilder> 
        getResultsFieldBuilder() {
      if (resultsBuilder_ == null) {
        resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.aserto.directory.common.v3.ObjectIdentifier, com.aserto.directory.common.v3.ObjectIdentifier.Builder, com.aserto.directory.common.v3.ObjectIdentifierOrBuilder>(
                results_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        results_ = null;
      }
      return resultsBuilder_;
    }

    private com.google.protobuf.Struct explanation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> explanationBuilder_;
    /**
     * <pre>
     * explanation of results
     * </pre>
     *
     * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
     * @return Whether the explanation field is set.
     */
    public boolean hasExplanation() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * explanation of results
     * </pre>
     *
     * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
     * @return The explanation.
     */
    public com.google.protobuf.Struct getExplanation() {
      if (explanationBuilder_ == null) {
        return explanation_ == null ? com.google.protobuf.Struct.getDefaultInstance() : explanation_;
      } else {
        return explanationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * explanation of results
     * </pre>
     *
     * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
     */
    public Builder setExplanation(com.google.protobuf.Struct value) {
      if (explanationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        explanation_ = value;
      } else {
        explanationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * explanation of results
     * </pre>
     *
     * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
     */
    public Builder setExplanation(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (explanationBuilder_ == null) {
        explanation_ = builderForValue.build();
      } else {
        explanationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * explanation of results
     * </pre>
     *
     * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
     */
    public Builder mergeExplanation(com.google.protobuf.Struct value) {
      if (explanationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          explanation_ != null &&
          explanation_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getExplanationBuilder().mergeFrom(value);
        } else {
          explanation_ = value;
        }
      } else {
        explanationBuilder_.mergeFrom(value);
      }
      if (explanation_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * explanation of results
     * </pre>
     *
     * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
     */
    public Builder clearExplanation() {
      bitField0_ = (bitField0_ & ~0x00000002);
      explanation_ = null;
      if (explanationBuilder_ != null) {
        explanationBuilder_.dispose();
        explanationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * explanation of results
     * </pre>
     *
     * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
     */
    public com.google.protobuf.Struct.Builder getExplanationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getExplanationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * explanation of results
     * </pre>
     *
     * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
     */
    public com.google.protobuf.StructOrBuilder getExplanationOrBuilder() {
      if (explanationBuilder_ != null) {
        return explanationBuilder_.getMessageOrBuilder();
      } else {
        return explanation_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : explanation_;
      }
    }
    /**
     * <pre>
     * explanation of results
     * </pre>
     *
     * <code>.google.protobuf.Struct explanation = 3 [json_name = "explanation"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getExplanationFieldBuilder() {
      if (explanationBuilder_ == null) {
        explanationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getExplanation(),
                getParentForChildren(),
                isClean());
        explanation_ = null;
      }
      return explanationBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList trace_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTraceIsMutable() {
      if (!trace_.isModifiable()) {
        trace_ = new com.google.protobuf.LazyStringArrayList(trace_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * trace information
     * </pre>
     *
     * <code>repeated string trace = 4 [json_name = "trace"];</code>
     * @return A list containing the trace.
     */
    public com.google.protobuf.ProtocolStringList
        getTraceList() {
      trace_.makeImmutable();
      return trace_;
    }
    /**
     * <pre>
     * trace information
     * </pre>
     *
     * <code>repeated string trace = 4 [json_name = "trace"];</code>
     * @return The count of trace.
     */
    public int getTraceCount() {
      return trace_.size();
    }
    /**
     * <pre>
     * trace information
     * </pre>
     *
     * <code>repeated string trace = 4 [json_name = "trace"];</code>
     * @param index The index of the element to return.
     * @return The trace at the given index.
     */
    public java.lang.String getTrace(int index) {
      return trace_.get(index);
    }
    /**
     * <pre>
     * trace information
     * </pre>
     *
     * <code>repeated string trace = 4 [json_name = "trace"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the trace at the given index.
     */
    public com.google.protobuf.ByteString
        getTraceBytes(int index) {
      return trace_.getByteString(index);
    }
    /**
     * <pre>
     * trace information
     * </pre>
     *
     * <code>repeated string trace = 4 [json_name = "trace"];</code>
     * @param index The index to set the value at.
     * @param value The trace to set.
     * @return This builder for chaining.
     */
    public Builder setTrace(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTraceIsMutable();
      trace_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * trace information
     * </pre>
     *
     * <code>repeated string trace = 4 [json_name = "trace"];</code>
     * @param value The trace to add.
     * @return This builder for chaining.
     */
    public Builder addTrace(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTraceIsMutable();
      trace_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * trace information
     * </pre>
     *
     * <code>repeated string trace = 4 [json_name = "trace"];</code>
     * @param values The trace to add.
     * @return This builder for chaining.
     */
    public Builder addAllTrace(
        java.lang.Iterable<java.lang.String> values) {
      ensureTraceIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, trace_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * trace information
     * </pre>
     *
     * <code>repeated string trace = 4 [json_name = "trace"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTrace() {
      trace_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * trace information
     * </pre>
     *
     * <code>repeated string trace = 4 [json_name = "trace"];</code>
     * @param value The bytes of the trace to add.
     * @return This builder for chaining.
     */
    public Builder addTraceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTraceIsMutable();
      trace_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aserto.directory.reader.v3.GetGraphResponse)
  }

  // @@protoc_insertion_point(class_scope:aserto.directory.reader.v3.GetGraphResponse)
  private static final com.aserto.directory.reader.v3.GetGraphResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aserto.directory.reader.v3.GetGraphResponse();
  }

  public static com.aserto.directory.reader.v3.GetGraphResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetGraphResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetGraphResponse>() {
    @java.lang.Override
    public GetGraphResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetGraphResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetGraphResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aserto.directory.reader.v3.GetGraphResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

